export const FETCH_CATEGORY = "FETCH_CATEGORY";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const SELECT_EDIT_CATEGORY = "SELECT_EDIT_CATEGORY";

export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

export const FETCH_PRODUCT = "FETCH_PRODUCT";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const SELECT_EDIT_PRODUCT = "SELECT_EDIT_PRODUCT";

export const FETCH_USER = "FETCH_USER";
export const ADD_USER = "ADD_USER";
export const DELETE_USER = "DELETE_USER";
export const UPDATE_USER = "UPDATE_USER";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const UPDATE_PASSWORD = "UPDATE_PASSWORD";

export const FETCH_CUSTOMER = "FETCH_CUSTOMER";
export const DELETE_CUSTOMER = "DELETE_CUSTOMER";
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";
export const SELECT_EDIT_CUSTOMER = "SELECT_EDIT_CUSTOMER";
